,dep,version,filepath,bloated,cve,affected versions,advisory
0,hydra-core,>=1.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
1,omegaconf,>=2.2.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
2,imageio-ffmpeg,>=0.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
3,attrs,>=19.1.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
4,gym,">=0.22.0,<0.23.1",/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
5,tqdm,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
6,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
7,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
8,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
9,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
10,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
11,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
12,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
13,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
14,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
15,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
16,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
17,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
18,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
19,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
20,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
21,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
22,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
23,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
24,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
25,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
26,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
27,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
28,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
29,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
30,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
31,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
32,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
33,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
34,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
35,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
36,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
37,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
38,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
39,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
40,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
41,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
42,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
43,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
44,numpy-quaternion,>=2019.3.18.14.33.20,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
45,scipy,>=1.10.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
46,numba,>=0.44.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,PVE-2021-38983,<0.49.0,"Numba 0.49.0 fixes a frame injection vulnerability in the dispatcher tracing path, that lead to DoS."
47,pickle5,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,no one,no one,no one
48,imageio,>=2.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,PVE-2021-37902,<2.6.0,"Imageio 2.6.0 fixes a code injection vulnerability for Windows users that have dcmtk installed, and where an attacker can set the filename.
https://github.com/imageio/imageio/commit/5b398716d518cd14e8b978ea3cd8ec6c0236c1d8"
49,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
50,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
51,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
52,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
53,hydra-core,>=1.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
54,omegaconf,>=2.2.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
55,imageio-ffmpeg,>=0.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
56,attrs,>=19.1.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
57,gym,">=0.22.0,<0.23.1",/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
58,tqdm,>=4.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
59,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
60,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
61,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
62,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
63,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
64,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
65,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
66,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
67,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
68,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
69,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
70,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
71,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
72,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
73,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
74,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
75,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
76,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
77,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
78,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
79,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
80,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
81,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
82,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
83,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
84,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
85,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
86,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
87,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
88,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
89,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
90,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
91,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
92,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
93,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
94,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
95,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
96,opencv-python,>=3.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
97,numpy-quaternion,>=2019.3.18.14.33.20,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
98,scipy,>=1.10.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
99,numba,>=0.44.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,PVE-2021-38983,<0.49.0,"Numba 0.49.0 fixes a frame injection vulnerability in the dispatcher tracing path, that lead to DoS."
100,pickle5,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
101,imageio,>=2.2.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,PVE-2021-37902,<2.6.0,"Imageio 2.6.0 fixes a code injection vulnerability for Windows users that have dcmtk installed, and where an attacker can set the filename.
https://github.com/imageio/imageio/commit/5b398716d518cd14e8b978ea3cd8ec6c0236c1d8"
102,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
103,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
104,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
105,numpy,>=1.20.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
106,torch,>=1.3.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
107,tensorboard,==2.8.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
108,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
109,protobuf,==3.20.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
110,moviepy,>=1.0.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
111,ifcfg,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
112,faster_fifo,>=1.4.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
113,threadpoolctl,>=3.1.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
114,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16225,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mp_flags, mdb_page_touch does not properly set up mc->mc_pg[mc->top], leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
115,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16226,">=0,<0.98","An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
116,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16228,">=0,<0.98",An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.
117,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16224,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of md_flags, mdb_node_add does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
118,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,CVE-2019-16227,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
119,webdataset,==0.1.40,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-lab/setup.py,False,no one,no one,no one
120,torch,>=1.3.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
121,tensorboard,==2.8.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/requirements.txt,False,no one,no one,no one
122,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/requirements.txt,False,no one,no one,no one
123,protobuf,==3.20.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/requirements.txt,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
124,moviepy,>=1.0.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/requirements.txt,False,no one,no one,no one
125,ifcfg,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/ddppo/requirements.txt,False,no one,no one,no one
126,faster_fifo,>=1.4.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/ver/requirements.txt,False,no one,no one,no one
127,threadpoolctl,>=3.1.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/ver/requirements.txt,False,no one,no one,no one
128,faster_fifo,==1.4.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/ver/ci-requirements.txt,False,no one,no one,no one
129,threadpoolctl,==3.1.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/rl/ver/ci-requirements.txt,False,no one,no one,no one
130,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,CVE-2019-16225,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mp_flags, mdb_page_touch does not properly set up mc->mc_pg[mc->top], leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
131,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,CVE-2019-16226,">=0,<0.98","An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
132,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,CVE-2019-16228,">=0,<0.98",An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.
133,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,CVE-2019-16224,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of md_flags, mdb_node_add does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
134,lmdb,>=0.98,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,CVE-2019-16227,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
135,webdataset,==0.1.40,/home/daniele/git/NICHE_projects/Repo/Cloneables/habitat-api/habitat-baselines/habitat_baselines/il/requirements.txt,False,no one,no one,no one
