,dep,version,filepath,bloated,cve,affected versions,advisory
0,pyyaml,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2017-18342,<4,Pyyaml before 4 uses ``yaml.load`` which has been assigned CVE-2017-18342.
1,pyyaml,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-1747,<5.3.1,"Pyyaml 5.3.1 includes a fix for CVE-2020-1747: A vulnerability was discovered in the PyYAML library in versions before 5.3.1, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. An attacker could use this flaw to execute arbitrary code on the system by abusing the python/object/new constructor."
2,pyyaml,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-14343,<5.4,"Pyyaml version 5.4 includes a fix for CVE-2020-14343: A vulnerability was discovered in the PyYAML library in versions before 5.4, where it is susceptible to arbitrary code execution when it processes untrusted YAML files through the full_load method or with the FullLoader loader. Applications that use the library to process untrusted input may be vulnerable to this flaw. This flaw allows an attacker to execute arbitrary code on the system by abusing the python/object/new constructor. This flaw is due to an incomplete fix for CVE-2020-1747.
https://bugzilla.redhat.com/show_bug.cgi?id=1860466"
3,pyyaml,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2019-20477,">=5.1,<=5.1.2","PyYAML 5.1 through 5.1.2 has insufficient restrictions on the load and load_all functions because of a class deserialization issue, e.g., Popen is a class in the subprocess module. See CVE-2019-20477. NOTE: this issue exists because of an incomplete fix for CVE-2017-18342."
4,packaging,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,no one,no one,no one
5,regex,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,no one,no one,no one
6,yapf,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,no one,no one,no one
7,mmengine,>=0.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,no one,no one,no one
8,addict,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,no one,no one,no one
9,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-1932,<2.3.1,pillow before 2.3.1 makes insecure use of tempfile.mktemp (CVE-2014-1932).
10,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-1933,<2.3.1,pillow before 2.3.1 makes insecure use of tempfile.mktemp (CVE-2014-1933).
11,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-3589,"<2.3.2,>=2.5.0,<2.5.2","Pillow versions 2.3.2 and 2.5.2 include a fix for CVE-2014-3589: PIL/IcnsImagePlugin.py in Python Imaging Library (PIL) and Pillow before 2.3.2 and 2.5.x before 2.5.2 allows remote attackers to cause a denial of service via a crafted block size.
https://github.com/python-pillow/Pillow/commit/205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d"
12,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-3007,<2.5.0,"Pillow 2.5.0 includes a fix that prevents shell injection.
https://github.com/python-pillow/Pillow/pull/731"
13,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-3598,<2.5.3,pillow before 2.5.3 is vulnerable to a DoS in the Jpeg2KImagePlugin.
14,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-9601,<2.6.2,Pillow before 2.6.2 is vulnerable to a PNG decompression DoS (CVE-2014-9601).
15,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-0775,<3.1.1,Buffer overflow in the ImagingFliDecode function in libImaging/FliDecode.c in Pillow before 3.1.1 allows remote attackers to cause a denial of service (crash) via a crafted FLI file.
16,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-0740,<3.1.1,Buffer overflow in the ImagingLibTiffDecode function in libImaging/TiffDecode.c in Pillow before 3.1.1 allows remote attackers to overwrite memory via a crafted TIFF file.
17,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-2533,<3.1.1,Buffer overflow in the ImagingPcdDecode function in PcdDecode.c in Pillow before 3.1.1 and Python Imaging Library (PIL) 1.1.7 and earlier allows remote attackers to cause a denial of service (crash) via a crafted PhotoCD file.
18,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-4009,<3.1.1,"Integer overflow in the ImagingResampleHorizontal function in libImaging/Resample.c in Pillow before 3.1.1 allows remote attackers to have unspecified impact via negative values of the new size, which triggers a heap-based buffer overflow."
19,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-3076,<3.1.2,pillow before 3.1.2 is vulnerable to an integer overflow in Jpeg2KEncode.c causing a buffer overflow. CVE-2016-3076.
20,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-9189,<3.3.2,"Pillow before 3.3.2 allows context-dependent attackers to obtain sensitive information by using the ""crafted image file"" approach, related to an ""Integer Overflow"" issue affecting the Image.core.map_buffer in map.c component."
21,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2016-9190,<3.3.2,"Pillow before 3.3.2 allows context-dependent attackers to execute arbitrary code by using the ""crafted image file"" approach, related to an ""Insecure Sign Extension"" issue affecting the ImagingNew in Storage.c component."
22,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2019-16865,<6.2.0,"Pillow 6.2.0 includes a fix for CVE-2019-16865: An issue was discovered in Pillow before 6.2.0. When reading specially crafted invalid image files, the library can either allocate very large amounts of memory or take an extremely long period of time to process the image."
23,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-5310,<6.2.2,"libImaging/TiffDecode.c in Pillow before 6.2.2 has a TIFF decoding integer overflow, related to realloc."
24,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-5311,<6.2.2,libImaging/SgiRleDecode.c in Pillow before 6.2.2 has an SGI buffer overflow.
25,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-5313,<6.2.2,libImaging/FliDecode.c in Pillow before 6.2.2 has an FLI buffer overflow.
26,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-5312,<6.2.2,libImaging/PcxDecode.c in Pillow before 6.2.2 has a PCX P mode buffer overflow.
27,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2019-19911,<6.2.2,"There is a DoS vulnerability in Pillow before 6.2.2 caused by FpxImagePlugin.py calling the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer."
28,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-10177,<7.1.0,Pillow before 7.1.0 has multiple out-of-bounds reads in libImaging/FliDecode.c.
29,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-10994,<7.1.0,"In libImaging/Jpeg2KDecode.c in Pillow before 7.1.0, there are multiple out-of-bounds reads via a crafted JP2 file."
30,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-10379,<7.1.0,"In Pillow before 7.1.0, there are two Buffer Overflows in libImaging/TiffDecode.c."
31,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-10378,<7.1.0,"In libImaging/PcxDecode.c in Pillow before 7.1.0, an out-of-bounds read can occur when reading PCX files where state->shuffle is instructed to read beyond state->buffer."
32,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-15999,<8.0.1,Pillow 8.0.1 updates 'FreeType' used in binary wheels to v2.10.4 to include a security fix.
33,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-35654,<8.1.0,Pillow 8.1.0 fixes TIFF OOB Write error. CVE-2020-35654 #5175.
34,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-35653,<8.1.0,"In Pillow before 8.1.0, PcxDecode has a buffer over-read when decoding a crafted PCX file because the user-supplied stride value is trusted for buffer calculations."
35,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-35655,<8.1.0,Pillow 8.1.0 includes a fix for SGI Decode buffer overrun. CVE-2020-35655 #5173.
36,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25289,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-25289: TiffDecode has a heap-based buffer overflow when decoding crafted YCbCr files because of certain interpretation conflicts with LibTIFF in RGBA mode. NOTE: this issue exists because of an incomplete fix for CVE-2020-35654.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
37,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25290,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-25290: In TiffDecode.c, there is a negative-offset memcpy with an invalid size.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
38,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-27922,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-27922: Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for an ICNS container, and thus an attempted memory allocation can be very large.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
39,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25291,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-25291: In TiffDecode.c, there is an out-of-bounds read in TiffreadRGBATile via invalid tile boundaries.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
40,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-27921,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-27921: Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for a BLP container, and thus an attempted memory allocation can be very large.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
41,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25293,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-25293: There is an out-of-bounds read in SGIRleDecode.c.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
42,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25292,<8.1.1,"Pillow 8.1.1 includes a fix for CVE-2021-25292: The PDF parser allows a regular expression DoS (ReDoS) attack via a crafted PDF file because of a catastrophic backtracking regex.
https://pillow.readthedocs.io/en/stable/releasenotes/8.1.1.html"
43,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25288,<8.2.0,"Pillow 8.2.0 includes a fix for CVE-2021-25288: There is an out-of-bounds read in J2kDecode, in j2ku_gray_i.
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
44,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-28677,<8.2.0,"Pillow version 8.2.0 includes a fix for CVE-2021-28677: For EPS data, the readline implementation used in EPSImageFile has to deal with any combination of \r and \n as line endings. It used an accidentally quadratic method of accumulating lines while looking for a line ending. A malicious EPS file could use this to perform a DoS of Pillow in the open phase, before an image was accepted for opening.
https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/
https://github.com/python-pillow/Pillow/pull/5377
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28677-fix-eps-dos-on-open"
45,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-28678,<8.2.0,"Pillow version 8.2.0 includes a fix for CVE-2021-28678: For BLP data, BlpImagePlugin did not properly check that reads (after jumping to file offsets) returned data. This could lead to a DoS where the decoder could be run a large number of times on empty data.
https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/
https://github.com/python-pillow/Pillow/pull/5377
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28678-fix-blp-dos"
46,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-28676,<8.2.0,"Pillow version 8.2.0 includes a fix for CVE-2021-28676: For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.
https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/MQHA5HAIBOYI3R6HDWCLAGFTIQP767FL/
https://github.com/python-pillow/Pillow/pull/5377
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-28676-fix-fli-dos"
47,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-25287,<8.2.0,"Pillow 8.2.0 includes a fix for CVE-2021-25287: There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.
https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#cve-2021-25287-cve-2021-25288-fix-oob-read-in-jpeg2kdecode"
48,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-34552,<8.3.0,"Pillow 8.3.0 includes a fix for CVE-2021-34552: Pillow through 8.2.0 and PIL (also known as Python Imaging Library) through 1.1.7 allow an attacker to pass controlled parameters directly into a convert function to trigger a buffer overflow in Convert.c
https://pillow.readthedocs.io/en/stable/releasenotes/8.3.0.html#buffer-overflow
https://pillow.readthedocs.io/en/stable/releasenotes/index.html"
49,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-22816,<9.0.0,"Pillow 9.0.0 includes a fix for CVE-2022-22816: path_getbbox in path.c in Pillow before 9.0.0 has a buffer over-read during initialization of ImagePath.Path.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
50,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,PVE-2021-44525,<9.0.0,"Pillow 9.0.0 excludes carriage return in PDF regex to help prevent ReDoS.
https://github.com/python-pillow/Pillow/pull/5912
https://github.com/python-pillow/Pillow/commit/43b800d933c996226e4d7df00c33fcbe46d97363"
51,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,PVE-2022-44524,<9.0.0,"Pillow 9.0.0 ensures JpegImagePlugin stops at the end of a truncated file to avoid Denial of Service attacks.
https://github.com/python-pillow/Pillow/pull/5921
https://github.com/advisories/GHSA-4fx9-vc88-q2xc"
52,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-22815,<9.0.0,"Pillow 9.0.0 includes a fix for CVE-2022-22815: path_getbbox in path.c in Pillow before 9.0.0 improperly initializes ImagePath.Path.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
53,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-24303,<9.0.1,Pillow before 9.0.1 allows attackers to delete files because spaces in temporary pathnames are mishandled.
54,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-22817,<9.0.1,"Pillow 9.0.1 includes a fix for CVE-2022-22817: PIL.ImageMath.eval in Pillow before 9.0.0 allows evaluation of arbitrary expressions, such as ones that use the Python exec method. A first patch was issued for version 9.0.0 but it did not prevent builtins available to lambda expressions.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"
55,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-45198,<9.2.0,Pillow before 9.2.0 performs Improper Handling of Highly Compressed GIF Data (Data Amplification).
56,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2020-11538,<=7.0.0,"In libImaging/SgiRleDecode.c in Pillow through 7.0.0, a number of out-of-bounds reads exist in the parsing of SGI image files, a different issue than CVE-2020-5311."
57,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-28675,">=0,<8.2.0",An issue was discovered in Pillow before 8.2.0. PSDImagePlugin.PsdImageFile lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on Image.open prior to Image.load.
58,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-27923,">=4.3.0,<8.1.1","Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for an ICO container, and thus an attempted memory allocation can be very large."
59,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-23437,">=5.2.0,<8.3.2","Pillow from 5.2.0 and before 8.3.2 is vulnerable to Regular Expression Denial of Service (ReDoS) via the getrgb function.
https://github.com/python-pillow/Pillow/commit/9e08eb8f78fdfd2f476e1b20b7cf38683754866b
https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html"
60,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-30595,">=9.1.0,<9.1.1",libImaging/TgaRleDecode.c in Pillow 9.1.0 has a heap buffer overflow in the processing of invalid TGA image files.
61,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,PVE-2023-55182,">=9.1.0,<9.3.0","Pillow 9.3.0 includes a security fix: Pillow will now decode the data in its natural CMYK mode, then convert it to RGB and rearrange the channels afterwards. Trying to load the data in an incorrect mode could result in a segmentation fault.
https://pillow.readthedocs.io/en/stable/releasenotes/9.3.0.html#decode-jpeg-compressed-blp1-data-in-original-mode"
62,Pillow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2022-45199,">=9.2.0,<9.3.0","Pillow before 9.3.0 allows denial of service via SAMPLESPERPIXEL.
https://pillow.readthedocs.io/en/stable/releasenotes/9.3.0.html#limit-samplesperpixel-to-avoid-runtime-dos"
63,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
64,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
65,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
66,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
67,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
68,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
69,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-1859,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1859: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/pull/4262"
70,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/runtime.txt,False,CVE-2014-1858,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1858: __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
71,pytest-runner,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/build.txt,False,no one,no one,no one
72,onnxruntime,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2022-1941,<1.13.1,Onnxruntime 1.13.1 updates 'protobuf' to v3.18.3 to include a security fix.
73,onnxruntime,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2022-25882,<1.13.1,"Onnxruntime 1.13.1 updates 'onnx' to v1.12.1 to fix a vulnerability that allows reading of tensor_data outside the model directory.
https://github.com/microsoft/onnxruntime/pull/12915"
74,onnx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2022-25882,<1.13.0,Onnx 1.13.0 includes a fix for CVE-2022-25882: Versions of the package onnx before 1.13.0 are vulnerable to Directory Traversal as the external_data field of the tensor proto can have a path to the file which is outside the model current directory or user-provided directory.
75,scipy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
76,lmdb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2019-16225,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mp_flags, mdb_page_touch does not properly set up mc->mc_pg[mc->top], leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
77,lmdb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2019-16226,">=0,<0.98","An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
78,lmdb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2019-16228,">=0,<0.98",An issue was discovered in py-lmdb 0.97. There is a divide-by-zero error in the function mdb_env_open2 if mdb_env_read_header obtains a zero value for a certain size field. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker.
79,lmdb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2019-16224,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of md_flags, mdb_node_add does not properly set up a memcpy destination, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
80,lmdb,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,CVE-2019-16227,">=0,<0.98","An issue was discovered in py-lmdb 0.97. For certain values of mn_flags, mdb_cursor_set triggers a memcpy with an invalid write operation within mdb_xcursor_init1. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
81,PyTurboJPEG,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,no one,no one,no one
82,tifffile,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,no one,no one,no one
83,coverage,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,no one,no one,no one
84,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,no one,no one,no one
85,onnxoptimizer,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/test.txt,False,no one,no one,no one
86,ninja,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/optional.txt,False,no one,no one,no one
87,psutil,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/optional.txt,False,CVE-2019-18874,<=5.6.5,psutil (aka python-psutil) through 5.6.5 can have a double free. This occurs because of refcount mishandling within a while or for loop that converts system data into a Python object. See CVE-2019-18874.
88,sphinx-copybutton,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
89,docutils,==0.16.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2009-5042,">=0.5,<0.6","Docutils 0.6 includes a fix for CVE-2009-5042: Python-docutils allows insecure usage of temporary files.
https://github.com/advisories/GHSA-cg75-6938-wx58"
90,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
91,myst-parser,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
92,pytorch_sphinx_theme,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
93,sphinx,==4.0.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
94,markdown,>=3.4.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
95,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
96,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
97,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
98,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
99,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
100,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
101,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
102,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
103,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
104,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
105,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
106,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
107,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
108,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
109,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
110,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
111,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
112,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
113,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
114,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
115,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
116,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
117,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
118,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
119,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
120,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
121,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
122,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
123,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
124,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
125,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
126,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
127,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
128,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
129,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
130,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
131,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
132,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
133,sphinx_markdown_tables,>=0.0.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,no one,no one,no one
134,urllib3,<2.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2020-7212,">=1.25.2,<=1.25.7","The _encode_invalid_chars function in util/url.py in the urllib3 library 1.25.2 through 1.25.7 for Python allows a denial of service (CPU consumption) because of an inefficient algorithm. The percent_encodings array contains all matches of percent encodings. It is not deduplicated. For a URL of length N, the size of percent_encodings may be up to O(N). The next step (normalize existing percent-encoded bytes) also takes up to O(N) for each step, so the total time is O(N^2). If percent_encodings were deduplicated, the time to compute _encode_invalid_chars would be O(kN), where k is at most 484 ((10+6*2)^2). See: CVE-2020-7212."
135,urllib3,<2.0.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/mmcv/requirements/docs.txt,False,CVE-2021-28363,">=1.26.0,<1.26.4","Urllib3 1.26.4 includes a fix for CVE-2021-28363: The urllib3 library 1.26.x before 1.26.4 for Python omits SSL certificate validation in some cases involving HTTPS to HTTPS proxies. The initial connection to the HTTPS proxy (if an SSLContext isn't given via proxy_config) doesn't verify the hostname of the certificate. This means certificates for different servers that still validate properly with the default urllib3 SSLContext will be silently accepted.
https://github.com/urllib3/urllib3/security/advisories/GHSA-5phf-pp7p-vc2r"
