,dep,version,filepath,bloated,cve,affected versions,advisory
0,importlib_metadata,!=3.8.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
1,numpy,>=1.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
2,numpy,>=1.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
3,numpy,>=1.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
4,numpy,>=1.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
5,numpy,>=1.16,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
6,pysparkling,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
7,python-json-logger,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
8,torch,==1.9.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
9,torchvision,==0.10.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
10,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2014-3589,"<2.3.2,>=2.5.0,<2.5.2","Pillow versions 2.3.2 and 2.5.2 include a fix for CVE-2014-3589: PIL/IcnsImagePlugin.py in Python Imaging Library (PIL) and Pillow before 2.3.2 and 2.5.x before 2.5.2 allows remote attackers to cause a denial of service via a crafted block size.
https://github.com/python-pillow/Pillow/commit/205e056f8f9b06ed7b925cf8aa0874bc4aaf8a7d"
11,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-22816,<9.0.0,"Pillow 9.0.0 includes a fix for CVE-2022-22816: path_getbbox in path.c in Pillow before 9.0.0 has a buffer over-read during initialization of ImagePath.Path.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
12,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,PVE-2021-44525,<9.0.0,"Pillow 9.0.0 excludes carriage return in PDF regex to help prevent ReDoS.
https://github.com/python-pillow/Pillow/pull/5912
https://github.com/python-pillow/Pillow/commit/43b800d933c996226e4d7df00c33fcbe46d97363"
13,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,PVE-2022-44524,<9.0.0,"Pillow 9.0.0 ensures JpegImagePlugin stops at the end of a truncated file to avoid Denial of Service attacks.
https://github.com/python-pillow/Pillow/pull/5921
https://github.com/advisories/GHSA-4fx9-vc88-q2xc"
14,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-22815,<9.0.0,"Pillow 9.0.0 includes a fix for CVE-2022-22815: path_getbbox in path.c in Pillow before 9.0.0 improperly initializes ImagePath.Path.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#fixed-imagepath-path-array-handling"
15,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-24303,<9.0.1,Pillow before 9.0.1 allows attackers to delete files because spaces in temporary pathnames are mishandled.
16,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-22817,<9.0.1,"Pillow 9.0.1 includes a fix for CVE-2022-22817: PIL.ImageMath.eval in Pillow before 9.0.0 allows evaluation of arbitrary expressions, such as ones that use the Python exec method. A first patch was issued for version 9.0.0 but it did not prevent builtins available to lambda expressions.
https://pillow.readthedocs.io/en/stable/releasenotes/9.0.1.html#security"
17,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-45198,<9.2.0,Pillow before 9.2.0 performs Improper Handling of Highly Compressed GIF Data (Data Amplification).
18,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-28675,">=0,<8.2.0",An issue was discovered in Pillow before 8.2.0. PSDImagePlugin.PsdImageFile lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on Image.open prior to Image.load.
19,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-27923,">=4.3.0,<8.1.1","Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for an ICO container, and thus an attempted memory allocation can be very large."
20,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-23437,">=5.2.0,<8.3.2","Pillow from 5.2.0 and before 8.3.2 is vulnerable to Regular Expression Denial of Service (ReDoS) via the getrgb function.
https://github.com/python-pillow/Pillow/commit/9e08eb8f78fdfd2f476e1b20b7cf38683754866b
https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html"
21,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-30595,">=9.1.0,<9.1.1",libImaging/TgaRleDecode.c in Pillow 9.1.0 has a heap buffer overflow in the processing of invalid TGA image files.
22,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,PVE-2023-55182,">=9.1.0,<9.3.0","Pillow 9.3.0 includes a security fix: Pillow will now decode the data in its natural CMYK mode, then convert it to RGB and rearrange the channels afterwards. Trying to load the data in an incorrect mode could result in a segmentation fault.
https://pillow.readthedocs.io/en/stable/releasenotes/9.3.0.html#decode-jpeg-compressed-blp1-data-in-original-mode"
23,pillow,!=8.3.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-45199,">=9.2.0,<9.3.0","Pillow before 9.3.0 allows denial of service via SAMPLESPERPIXEL.
https://pillow.readthedocs.io/en/stable/releasenotes/9.3.0.html#limit-samplesperpixel-to-avoid-runtime-dos"
24,dataclasses,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
25,timm,>=0.4.9,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
26,einops,>=0.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
27,flameprof,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
28,ipython,<8,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2023-24816,<8.10.0,"IPython 8.10.0 includes a fix for CVE-2023-24816: Versions prior to 8.10.0 are subject to a command injection vulnerability with very specific prerequisites. This vulnerability requires that the function 'IPython.utils.terminal.set_term_title' be called on Windows in a Python environment where ctypes is not available. The dependency on 'ctypes' in 'IPython.utils._process_win32' prevents the vulnerable code from ever being reached in the ipython binary. However, as a library that could be used by another tool 'set_term_title' could be called and hence introduce a vulnerability. If an attacker get untrusted input to an instance of this function they would be able to inject shell commands as current process and limited to the scope of the current process. As a workaround, users should ensure that any calls to the 'IPython.utils.terminal.set_term_title' function are done with trusted or filtered input.
https://github.com/ipython/ipython/security/advisories/GHSA-29gw-9793-fvw7"
29,ipython,<8,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2014-3429,">=0.12,<1.2","IPython Notebook 0.12 through 1.x before 1.2 does not validate the origin of websocket requests, which allows remote attackers to execute arbitrary code by leveraging knowledge of the kernel id and a crafted page."
30,ipython,<8,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2016-6524,">=2.0.0,<4.0.0",Ipython 4.0 includes a fix for CVE-2016-6524: Untrusted LaTeX output could be added to the page in a way that could execute javascript.
31,ipython,<8,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2015-4706,">=3.0.0,<3.2.0",Cross-site scripting (XSS) vulnerability in IPython 3.x before 3.2 allows remote attackers to inject arbitrary web script or HTML via vectors involving JSON error messages and the /api/contents path.
32,ipython,<8,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-21699,">=8.0.0a0,<8.0.1,>=7.17.0,<7.31.1,>=6.0.0a0,<7.16.3,<5.11","Ipython versions 8.0.1, 7.31.1, 7.16.3 and 5.11 include a fix for CVE-2022-21699: Affected versions are subject to an arbitrary code execution vulnerability achieved by not properly managing cross user temporary files. This vulnerability allows one user to run code as another on the same machine.
https://github.com/ipython/ipython/security/advisories/GHSA-pq7m-3gw7-gq5x"
33,jupyter-book,">=0.9.1,<0.14",/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
34,matplotlib,>=3.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
35,nbdime,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2021-41134,">=0,<1.1.1,>=2.0.0,<2.1.1,>=3.0.0,<3.1.1","nbdime provides tools for diffing and merging of Jupyter Notebooks. In affected versions a stored cross-site scripting (XSS) issue exists within the Jupyter-owned nbdime project. It appears that when reading the file name and path from disk, the extension does not sanitize the string it constructs before returning it to be displayed. The diffNotebookCheckpoint function within nbdime causes this issue. When attempting to display the name of the local notebook (diffNotebookCheckpoint), nbdime appears to simply append .ipynb to the name of the input file. The NbdimeWidget is then created, and the base string is passed through to the request API function. From there, the frontend simply renders the HTML tag and anything along with it. Users are advised to patch to the most recent version of the affected product."
36,nbstripout,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
37,scipy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
38,sphinx-book-theme,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
39,wheel,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-40898,<0.38.1,"Wheel 0.38.1 includes a fix for CVE-2022-40898: An issue discovered in Python Packaging Authority (PyPA) Wheel 0.37.1 and earlier allows remote attackers to cause a denial of service via attacker controlled input to wheel cli.
https://pyup.io/posts/pyup-discovers-redos-vulnerabilities-in-top-python-packages"
40,onnx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-25882,<1.13.0,Onnx 1.13.0 includes a fix for CVE-2022-25882: Versions of the package onnx before 1.13.0 are vulnerable to Directory Traversal as the external_data field of the tensor proto can have a path to the file which is outside the model current directory or user-provided directory.
41,onnxruntime,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-1941,<1.13.1,Onnxruntime 1.13.1 updates 'protobuf' to v3.18.3 to include a security fix.
42,onnxruntime,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-25882,<1.13.1,"Onnxruntime 1.13.1 updates 'onnx' to v1.12.1 to fix a vulnerability that allows reading of tensor_data outside the model directory.
https://github.com/microsoft/onnxruntime/pull/12915"
43,onnx-simplifier,>=0.2.9,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
44,protobuf,<4,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-1941,"<3.18.3,>=3.19.0rc0,<3.19.5,>=3.20.0rc0,<3.20.2,>=4.0.0rc0,<4.21.6","A parsing vulnerability for the MessageSet type in the ProtocolBuffers versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 3.21.5 for protobuf-cpp, and versions prior to and including 3.16.1, 3.17.3, 3.18.2, 3.19.4, 3.20.1 and 4.21.5 for protobuf-python can lead to out of memory failures. A specially crafted message with multiple key-value per elements creates parsing issues, and can lead to a Denial of Service against services receiving unsanitized input. We recommend upgrading to versions 3.18.3, 3.19.5, 3.20.2, 3.21.6 for protobuf-cpp and 3.18.3, 3.19.5, 3.20.2, 4.21.6 for protobuf-python. Versions for 3.16 and 3.17 are no longer updated."
45,coremltools,>=5.0b3,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
46,numpy,<1.24,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
47,cpplint,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
48,nbconvert,<7,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
49,nbval,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
50,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2016-1517,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2016-1517: OpenCV 3.0.0 allows remote attackers to cause a denial of service (segfault) via vectors involving corrupt chunks.
51,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12602,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12602: OpenCV through 3.3 has a denial of service (memory consumption) issue, as demonstrated by the 10-opencv-dos-memory-exhaust test case."
52,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12603,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12603: OpenCV through 3.3 has an invalid write in the cv::RLByteStream::getBytes function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 2-opencv-heapoverflow-fseek test case."
53,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12597,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12597: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread.
54,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12599,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12599: OpenCV through 3.3 has an out-of-bounds read error in the function icvCvt_BGRA2BGR_8u_C4C3R when reading an image file by using cv::imread.
55,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12606,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for CVE-2017-12606: OpenCV through 3.3 has an out-of-bounds write error in the function FillColorRow4 in utils.cpp when reading an image file by using cv::imread.
56,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12601,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12601: OpenCV through 3.3 has a buffer overflow in the cv::BmpDecoder::readData function in modules/imgcodecs/src/grfmt_bmp.cpp when reading an image file by using cv::imread, as demonstrated by the 4-buf-overflow-readData-memcpy test case."
57,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12604,<3.3.1.11,Opencv-python 3.3.1.11 includes a fix for  CVE-2017-12604: OpenCV through 3.3 has an out-of-bounds write error in the FillUniColor function in utils.cpp when reading an image file by using cv::imread.
58,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12600,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12600: OpenCV through 3.3 has a denial of service (CPU consumption) issue, as demonstrated by the 11-opencv-dos-cpu-exhaust test case."
59,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12598,<3.3.1.11,"Opencv-python 3.3.1.11 includes a fix for CVE-2017-12598: OpenCV through 3.3 has an out-of-bounds read error in the cv::RBaseStream::readBlock function in modules/imgcodecs/src/bitstrm.cpp when reading an image file by using cv::imread, as demonstrated by the 8-opencv-invalid-read-fread test case."
60,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-7317,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'libpng' to v1.6.37 to include a security fix.
61,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-0778,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
62,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-1292,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 update its dependency 'openssl' to v1_1_1o to include security fixes.
63,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-27406,"<3.4.18,>=4.0.0,<4.6.0",Opencv-python 3.4.18 and 4.6.0 pin its dependency 'freetype' to v2.12.1 to include a security fix.
64,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-19624,<4.1.0.25,"Opencv-python 4.1.0.25 includes a fix for CVE-2019-19624: An out-of-bounds read was discovered in OpenCV before 4.1.1. Specifically, variable coarsest_scale is assumed to be greater than or equal to finest_scale within the calc()/ocl_calc() functions in dis_flow.cpp. However, this is not true when dealing with small images, leading to an out-of-bounds read of the heap-allocated arrays Ux and Uy."
65,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-9423,<4.1.1.26,"Opencv-python 4.1.1.26 includes a fix for CVE-2019-9423: In opencv calls that use libpng, there is a possible out of bounds write due to a missing bounds check. This could lead to local escalation of privilege with no additional execution privileges required. User interaction is not required for exploitation."
66,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-15939,<4.1.1.26,Opencv-python 4.1.1.26 includes a fix for CVE-2019-15939: An issue was discovered in OpenCV 4.1.0. There is a divide-by-zero error in cv::HOGDescriptor::getDescriptorSize in modules/objdetect/src/hog.cpp.
67,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-16249,<4.1.2.30,Opencv-python 4.1.2.30 includes a fix for  CVE-2019-16249: OpenCV 4.1.1 has an out-of-bounds read in hal_baseline::v_load in core/hal/intrin_sse.hpp when called from computeSSDMeanNorm in modules/video/src/dis_flow.cpp.
68,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-37434,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'zlib' to v1.2.13 to include a security fix.
69,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-2097,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
70,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-1475,<4.7.0,Opencv-python 4.7.0 updates its C dependency 'FFmpeg' to v5.1.2 to include a security fix.
71,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2022-2068,<4.7.0,Opencv-python 4.7.0 updates its dependency 'OpenSSL' to v1.1.1s to include security fixes.
72,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
73,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
74,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
75,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
76,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
77,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
78,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
79,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
80,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
81,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
82,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
83,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
84,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-14492,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14492: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read/write in the function HaarEvaluator::OptFeature::calc in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
85,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-14491,">=4.0.0.21,<4.1.1.26,<3.4.7.28","Opencv-python 4.1.1.26 and 3.4.7.28 include a fix for CVE-2019-14491: An issue was discovered in OpenCV before 3.4.7 and 4.x before 4.1.1. There is an out of bounds read in the function cv::predictOrdered<cv::HaarEvaluator> in modules/objdetect/src/cascadedetect.hpp, which leads to denial of service."
86,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-5063,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for CVE-2019-5063: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV 4.1.0. A specially crafted XML file can cause a buffer overflow, resulting in multiple heap corruptions and potential code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
87,opencv-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2019-5064,">=4.0.0.21,<4.2.0.32","Opencv-python 4.2.0.32 includes a fix for  CVE-2019-5064: An exploitable heap buffer overflow vulnerability exists in the data structure persistence functionality of OpenCV, before version 4.2.0. A specially crafted JSON file can cause a buffer overflow, resulting in multiple heap corruptions and potentially code execution. An attacker can provide a specially crafted file to trigger this vulnerability."
88,pycodestyle,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
89,pylint,<2.9.4,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,PVE-2022-45185,<2.13.0,"Pylint 2.13.0 fixes a crash when using the doc_params extension.
https://github.com/PyCQA/pylint/issues/5322"
90,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
91,requests,>=2.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2018-18074,<=2.19.1,"Requests before 2.20.0 sends an HTTP Authorization header to an http URI upon receiving a same-hostname https-to-http redirect, which makes it easier for remote attackers to discover credentials by sniffing the network."
92,requests,>=2.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2015-2296,">=2.1,<=2.5.3",The resolve_redirects function in sessions.py in requests 2.1.0 through 2.5.3 allows remote attackers to conduct session fixation attacks via a cookie without a host value in a redirect.
93,requests,>=2.6.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,CVE-2023-32681,">=2.3.0,<2.31.0","Requests is a HTTP library. Since Requests 2.3.0, Requests has been leaking Proxy-Authorization headers to destination servers when redirected to an HTTPS endpoint. This is a product of how we use 'rebuild_proxies' to reattach the 'Proxy-Authorization' header to requests. For HTTP connections sent through the tunnel, the proxy will identify the header in the request itself and remove it prior to forwarding to the destination server. However when sent over HTTPS, the 'Proxy-Authorization' header must be sent in the CONNECT request as the proxy has no visibility into the tunneled request. This results in Requests forwarding proxy credentials to the destination server unintentionally, allowing a malicious actor to potentially exfiltrate sensitive information. This issue has been patched in version 2.31.0.

"
94,tabulate,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
95,thop,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
96,pycocotools,">=2.0.1,!=2.0.5,!=2.0.6",/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
97,xtcocotools,>=1.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/openpifpaf/setup.py,False,no one,no one,no one
