,dep,version,filepath,bloated,cve,affected versions,advisory
0,gensim,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
1,wrapt,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
2,spacy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
3,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
4,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
5,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
6,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
7,torchmetrics,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
8,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
9,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
10,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
11,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
12,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
13,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
14,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
15,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
16,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
17,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
18,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
19,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
20,einops,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
21,pyarrow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2019-12410,">=0.12.0,<=0.14.1","While investigating UBSAN errors in https://github.com/apache/arrow/pull/5365 it was discovered Apache Arrow versions 0.12.0 to 0.14.1 left memory Array data uninitialized when reading RLE null data from parquet. This affected the C++, Python, Ruby and R implementations. The uninitialized memory could potentially be shared if are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
22,pyarrow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2019-12408,">=0.14.0,<=0.14.1","It was discovered that the C++ implementation (which underlies the R, Python and Ruby implementations) of Apache Arrow 0.14.0 to 0.14.1 had a uninitialized memory bug when building arrays with null values in some cases. This can lead to uninitialized memory being unintentionally shared if Arrow Arrays are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
23,fastparquet,>=0.8.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
24,imutils,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
25,scipy,>=1.7.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
26,pandas,>=1.3.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
27,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,no one,no one,no one
28,scikit-learn,>=1.0.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2020-13092,">=0,<0.23.1","** DISPUTED ** scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
29,scikit-learn,>=1.0.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2020-28975,">=0,<0.24.dev0","** DISPUTED ** svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array. NOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute."
30,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
31,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
32,pytest-cov,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
33,codecov,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2019-10800,<2.0.16,"Codecov 2.0.16 includes a fix for CVE-2019-10800: Remote code execution. The vulnerability exists due to improper sanitization of ""gcov"" arguments before being provided to the ""popen"" method. A remote authenticated attacker can execute arbitrary OS commands on the target system."
34,codecov,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2021-38075,<2.0.17,Codecov 2.0.17 fixes a reported command injection vulnerability.
35,sphinx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-11023,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
36,sphinx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-11022,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
37,sphinx_rtd_theme,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
38,recommonmark,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
39,sphinx-markdown-tables,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
40,sphinx-copybutton,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
41,sphinx-autodoc-typehints,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
42,black,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
43,isort,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
44,flake8,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
45,gensim,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
46,wrapt,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
47,spacy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
48,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
49,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
50,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
51,numpy,>=1.21.6,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
52,torchmetrics,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
53,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
54,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
55,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
56,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
57,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
58,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
59,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
60,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
61,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
62,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
63,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
64,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
65,einops,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
66,pyarrow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2019-12410,">=0.12.0,<=0.14.1","While investigating UBSAN errors in https://github.com/apache/arrow/pull/5365 it was discovered Apache Arrow versions 0.12.0 to 0.14.1 left memory Array data uninitialized when reading RLE null data from parquet. This affected the C++, Python, Ruby and R implementations. The uninitialized memory could potentially be shared if are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
67,pyarrow,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2019-12408,">=0.14.0,<=0.14.1","It was discovered that the C++ implementation (which underlies the R, Python and Ruby implementations) of Apache Arrow 0.14.0 to 0.14.1 had a uninitialized memory bug when building arrays with null values in some cases. This can lead to uninitialized memory being unintentionally shared if Arrow Arrays are transmitted over the wire (for instance with Flight) or persisted in the streaming IPC and file formats."
68,fastparquet,>=0.8.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
69,imutils,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
70,scipy,>=1.7.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
71,pandas,>=1.3.5,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
72,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
73,scikit-learn,>=1.0.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-13092,">=0,<0.23.1","** DISPUTED ** scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
74,scikit-learn,>=1.0.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-28975,">=0,<0.24.dev0","** DISPUTED ** svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array. NOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute."
75,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
76,mkdocs-autolinks-plugin,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
77,mkdocstrings,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
78,mkdocstrings-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
79,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2022-47794,<1.3.0,"Mkdocs 1.3.0 fixes an XSS vulnerability which was present when using the search function in built-in themes.
https://github.com/mkdocs/mkdocs/commit/5cf196361bb0f8364f667ed98888ffa064982efa"
80,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-40978,">=0,<1.2.3","The mkdocs 1.2.2 built-in dev-server allows directory traversal using the port 8000, enabling remote exploitation to obtain :sensitive information."
81,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2021-32121,<1.0.0,mkdocs-material before 1.0.0 uses _blank targets on links which make it vulnerable to Cross Site Scripting attacks.
82,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2022-44813,<5.0.0,Mkdocs-material 5.0.0 updates its NPM dependency 'acorn' to v6.4.1 to include a security fix.
83,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-8203,<5.5.0,Mkdocs-material 5.5.0 updates its dependency 'lodash' to v4.17.19 to include a security fix.
84,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-7788,<6.2.0,Mkdocs-material 6.2.0 updates its dependency 'ini' to v1.3.7 to include a security fix.
85,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2021-39706,<7.0.6,Mkdocs-material 7.0.6 improves the security of the Docker image.
86,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-23364,<7.1.6,Mkdocs-material 7.1.6 updates its dependency 'browserslist' to v4.16.6 to include a security fix.
87,mkdocs-git-authors-plugin,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
88,mkdocs-jupyter,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,no one,no one,no one
89,pandas,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
90,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
91,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
92,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
93,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
94,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
95,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
96,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2014-1859,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1859: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/pull/4262"
97,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2014-1858,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1858: __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
98,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,PVE-2022-52255,<0.24.2,"Scikit-learn 0.24.2 includes a fix for a ReDoS vulnerability.
https://github.com/scikit-learn/scikit-learn/issues/19522"
99,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-13092,">=0,<0.23.1","** DISPUTED ** scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
100,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2020-28975,">=0,<0.24.dev0","** DISPUTED ** svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array. NOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute."
101,scipy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/setup.py,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
102,mkdocs-autolinks-plugin,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,no one,no one,no one
103,mkdocstrings,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,no one,no one,no one
104,mkdocstrings-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,no one,no one,no one
105,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,PVE-2022-47794,<1.3.0,"Mkdocs 1.3.0 fixes an XSS vulnerability which was present when using the search function in built-in themes.
https://github.com/mkdocs/mkdocs/commit/5cf196361bb0f8364f667ed98888ffa064982efa"
106,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,CVE-2021-40978,">=0,<1.2.3","The mkdocs 1.2.2 built-in dev-server allows directory traversal using the port 8000, enabling remote exploitation to obtain :sensitive information."
107,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,PVE-2021-32121,<1.0.0,mkdocs-material before 1.0.0 uses _blank targets on links which make it vulnerable to Cross Site Scripting attacks.
108,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,PVE-2022-44813,<5.0.0,Mkdocs-material 5.0.0 updates its NPM dependency 'acorn' to v6.4.1 to include a security fix.
109,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,CVE-2020-8203,<5.5.0,Mkdocs-material 5.5.0 updates its dependency 'lodash' to v4.17.19 to include a security fix.
110,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,CVE-2020-7788,<6.2.0,Mkdocs-material 6.2.0 updates its dependency 'ini' to v1.3.7 to include a security fix.
111,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,PVE-2021-39706,<7.0.6,Mkdocs-material 7.0.6 improves the security of the Docker image.
112,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,CVE-2021-23364,<7.1.6,Mkdocs-material 7.1.6 updates its dependency 'browserslist' to v4.16.6 to include a security fix.
113,mkdocs-git-authors-plugin,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,no one,no one,no one
114,mkdocs-jupyter,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/mkdocs/requirements.txt,False,no one,no one,no one
115,sphinx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2020-11023,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
116,sphinx,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2020-11022,<3.0.4,Sphinx 3.0.4 updates jQuery version from 3.4.1 to 3.5.1 for security reasons.
117,spacy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
118,sphinx-autodoc-typehints,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
119,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-1000450,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/utils.cpp, functions FillUniColor and FillUniGray do not check the input length, which can lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects Opencv 3.3 (corresponding with OpenCV-Python 3.3.0.9) and earlier."
120,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-12864,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function ReadNumber did not checkout the input length, which lead to integer overflow. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding with OpenCV-Python version 3.3.0.9) and earlier."
121,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2016-1516,">=0,<3.3.1.11",OpenCV 3.0.0 has a double free issue that allows attackers to execute arbitrary code. This issue was fixed in OpenCV version 3.3.1 (corresponding to OpenCV-Python and and OpenCV-Contrib-Python 3.3.1.11).
122,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-12605,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) through 3.3 (corresponding to OpenCV-Python and OpenCV-Contrib-Python 3.3.0.9) has an out-of-bounds write error in the FillColorRow8 function in utils.cpp when reading an image file by using cv::imread.
123,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-12863,">=0,<3.3.1.11","In opencv/modules/imgcodecs/src/grfmt_pxm.cpp, function PxMDecoder::readData has an integer overflow when calculate src_pitch. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
124,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-12862,">=0,<3.3.1.11","In modules/imgcodecs/src/grfmt_pxm.cpp, the length of buffer AutoBuffer _src is small than expected, which will cause copy buffer overflow later. If the image is from remote, may lead to remote code execution or denial of service. This affects OpenCV 3.3 (corresponding to OpenCV-Python 3.3.0.9) and earlier."
125,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-14136,">=0,<3.3.1.11",OpenCV (Open Source Computer Vision Library) 3.3 (corresponding to OpenCV-Python 3.3.0.9) has an out-of-bounds write error in the function FillColorRow1 in utils.cpp when reading an image file by using cv::imread. NOTE: this vulnerability exists because of an incomplete fix for CVE-2017-12597.
126,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-17760,">=0,<3.4.0.12","OpenCV 3.3.1 (corresponding with opencv-python and opencv-contrib-python 3.3.1.11) has a Buffer Overflow in the cv::PxMDecoder::readData function in grfmt_pxm.cpp, because an incorrect size value is used."
127,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-18009,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer over-read exists in the function cv::HdrDecoder::checkSignature in modules/imgcodecs/src/grfmt_hdr.cpp."
128,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2018-5268,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponding with OpenCV-Python 3.3.1.11), a heap-based buffer overflow happens in cv::Jpeg2KDecoder::readComponent8u in modules/imgcodecs/src/grfmt_jpeg2000.cpp when parsing a crafted image file."
129,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2018-5269,">=0,<3.4.1.15","In OpenCV 3.3.1 (corresponds with OpenCV-Python 3.3.1.11), an assertion failure happens in cv::RBaseStream::setPos in modules/imgcodecs/src/bitstrm.cpp because of an incorrect integer cast."
130,opencv-contrib-python,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2019-14493,">=0,<4.1.1.26",An issue was discovered in OpenCV before 4.1.1 (OpenCV-Python before 4.1.1.26). There is a NULL pointer dereference in the function cv::XMLParser::parse at modules/core/src/persistence.cpp.
131,sphinx_rtd_theme,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
132,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
133,gensim,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
134,wrapt,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
135,einops,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
136,recommonmark,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
137,pandas,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2020-13091,">=0,<1.0.4","** DISPUTED ** pandas through 1.0.3 can unserialize and execute commands from an untrusted file that is passed to the read_pickle() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the read_pickle() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
138,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
139,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
140,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
141,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
142,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
143,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
144,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2014-1859,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1859: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/pull/4262"
145,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2014-1858,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1858: __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
146,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,PVE-2022-52255,<0.24.2,"Scikit-learn 0.24.2 includes a fix for a ReDoS vulnerability.
https://github.com/scikit-learn/scikit-learn/issues/19522"
147,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2020-13092,">=0,<0.23.1","** DISPUTED ** scikit-learn (aka sklearn) through 0.23.0 can unserialize and execute commands from an untrusted file that is passed to the joblib.load() function, if __reduce__ makes an os.system call. NOTE: third parties dispute this issue because the joblib.load() function is documented as unsafe and it is the user's responsibility to use the function in a secure manner."
148,scikit-learn,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2020-28975,">=0,<0.24.dev0","** DISPUTED ** svm_predict_values in svm.cpp in Libsvm v324, as used in scikit-learn 0.23.2 and other products, allows attackers to cause a denial of service (segmentation fault) via a crafted model SVM (introduced via pickle, json, or any other model permanence standard) with a large value in the _n_support array. NOTE: the scikit-learn vendor's position is that the behavior can only occur if the library's API is violated by an application that changes a private attribute."
149,sphinx-copybutton,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
150,tqdm,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2016-10075,<4.11.2,The tqdm._version module in tqdm versions before 4.11.2 allows local users to execute arbitrary code via a crafted repo with a malicious git log in the current working directory.
151,torchmetrics,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
152,sphinx-markdown-tables,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
153,torchvision,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
154,scipy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,CVE-2013-4251,">=0,<0.12.1",The scipy.weave component in SciPy before 0.12.1 creates insecure temporary directories.
155,imutils,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/pytorch-widedeep/docs/requirements.txt,False,no one,no one,no one
