,dep,version,filepath,bloated,cve,affected versions,advisory
0,numpy,>=1.16.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
1,numpy,>=1.16.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
2,numpy,>=1.16.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
3,numpy,>=1.16.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
4,termcolor,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,no one,no one,no one
5,torch,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
6,GitPython,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,PVE-2022-52518,<3.1.27,"Gitpython 3.1.27 includes a fix for a REDoS vulnerability.
https://github.com/gitpython-developers/GitPython/commit/75f4f63ab3856a552f06082aabf98845b5fa21e3"
7,GitPython,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,CVE-2022-24439,<3.1.30,"Gitpython 3.1.30 includes a fix for CVE-2022-24439: Gitpython is vulnerable to Remote Code Execution (RCE) due to improper user input validation, which makes it possible to inject a maliciously crafted remote URL into the clone command. Exploiting this vulnerability is possible because the library makes external calls to git without sufficient sanitization of input arguments.
https://github.com/gitpython-developers/GitPython/pull/1521"
8,gitdb2,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,no one,no one,no one
9,matplotlib,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/rlcard/setup.py,False,no one,no one,no one
