,dep,version,filepath,bloated,cve,affected versions,advisory
0,setuptools_rust,==1.5.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements.txt,False,no one,no one,no one
1,toml,==0.10.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements.txt,False,no one,no one,no one
2,setuptools,==65.6.3,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements.txt,False,no one,no one,no one
3,numpy,==1.24.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements.txt,False,no one,no one,no one
4,mkdocstrings,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,no one,no one,no one
5,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,PVE-2021-32121,<1.0.0,mkdocs-material before 1.0.0 uses _blank targets on links which make it vulnerable to Cross Site Scripting attacks.
6,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,PVE-2022-44813,<5.0.0,Mkdocs-material 5.0.0 updates its NPM dependency 'acorn' to v6.4.1 to include a security fix.
7,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,CVE-2020-8203,<5.5.0,Mkdocs-material 5.5.0 updates its dependency 'lodash' to v4.17.19 to include a security fix.
8,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,CVE-2020-7788,<6.2.0,Mkdocs-material 6.2.0 updates its dependency 'ini' to v1.3.7 to include a security fix.
9,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,PVE-2021-39706,<7.0.6,Mkdocs-material 7.0.6 improves the security of the Docker image.
10,mkdocs-material,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,CVE-2021-23364,<7.1.6,Mkdocs-material 7.1.6 updates its dependency 'browserslist' to v4.16.6 to include a security fix.
11,mike,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,no one,no one,no one
12,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,PVE-2022-47794,<1.3.0,"Mkdocs 1.3.0 fixes an XSS vulnerability which was present when using the search function in built-in themes.
https://github.com/mkdocs/mkdocs/commit/5cf196361bb0f8364f667ed98888ffa064982efa"
13,mkdocs,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/requirements-docs.txt,False,CVE-2021-40978,">=0,<1.2.3","The mkdocs 1.2.2 built-in dev-server allows directory traversal using the port 8000, enabling remote exploitation to obtain :sensitive information."
14,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2017-12852,<1.13.2,"Numpy 1.13.2 includes a fix for CVE-2017-12852: The numpy.pad function in Numpy 1.13.1 and older versions is missing input validation. An empty list or ndarray will stick into an infinite loop, which can allow attackers to cause a DoS attack.
https://github.com/numpy/numpy/issues/9560#issuecomment-322395292"
15,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2019-6446,<1.16.3,"Numpy 1.16.3 includes a fix for CVE-2019-6446: It uses the pickle Python module unsafely, which allows remote attackers to execute arbitrary code via a crafted serialized object, as demonstrated by a numpy.load call.
https://github.com/numpy/numpy/commit/89b688732b37616c9d26623f81aaee1703c30ffb"
16,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2021-33430,<1.21.0rc1,"Numpy 1.21.0rc1 includes a fix for CVE-2021-33430: A Buffer Overflow vulnerability in the PyArray_NewFromDescr_int function of ctors.c when specifying arrays of large dimensions (over 32) from Python code, which could let a malicious user cause a Denial of Service. 
NOTE: The vendor does not agree this is a vulnerability. In (very limited) circumstances a user may be able provoke the buffer overflow, the user is most likely already privileged to at least provoke denial of service by exhausting memory. Triggering this further requires the use of uncommon API (complicated structured dtypes), which is very unlikely to be available to an unprivileged user.
https://github.com/numpy/numpy/issues/18939"
17,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2021-34141,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-34141: An incomplete string comparison in the numpy.core component in NumPy before 1.22.0 allows attackers to trigger slightly incorrect copying by constructing specific string objects. 
NOTE: the vendor states that this reported code behavior is ""completely harmless.""
https://github.com/numpy/numpy/issues/18993"
18,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2021-41496,<1.22.0,"Numpy 1.22.0 includes a fix for CVE-2021-41496: Buffer overflow in the array_from_pyobj function of fortranobject.c, which allows attackers to conduct a Denial of Service attacks by carefully constructing an array with negative values. 
NOTE: The vendor does not agree this is a vulnerability; the negative dimensions can only be created by an already privileged user (or internally).
https://github.com/numpy/numpy/issues/19000"
19,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
20,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2014-1859,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1859: (1) core/tests/test_memmap.py, (2) core/tests/test_multiarray.py, (3) f2py/f2py2e.py, and (4) lib/tests/test_io.py in NumPy before 1.8.1 allow local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/pull/4262"
21,numpy,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,CVE-2014-1858,<1.8.1,"Numpy 1.8.1 includes a fix for CVE-2014-1858: __init__.py in f2py in NumPy before 1.8.1 allows local users to write to arbitrary files via a symlink attack on a temporary file.
https://github.com/numpy/numpy/commit/0bb46c1448b0d3f5453d5182a17ea7ac5854ee15"
22,pytest,==*,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/ffi/py/setup.py,False,no one,no one,no one
23,numpy,==1.22.0,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/linalg/cost_model/train/requirements.txt,False,CVE-2021-41495,<1.22.2,"Numpy 1.22.2  includes a fix for CVE-2021-41495: Null Pointer Dereference vulnerability exists in numpy.sort in NumPy in the PyArray_DescrNew function due to missing return-value validation, which allows attackers to conduct DoS attacks by repetitively creating sort arrays. 
NOTE: While correct that validation is missing, an error can only occur due to an exhaustion of memory. If the user can exhaust memory, they are already privileged. Further, it should be practically impossible to construct an attack which can target the memory exhaustion to occur at exactly this place.
https://github.com/numpy/numpy/issues/19038"
24,torch,==1.13.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/linalg/cost_model/train/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
25,torchvision,==0.4.2,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/examples/pytorch-resnet/requirements.txt,False,no one,no one,no one
26,torch,==1.13.1,/home/daniele/git/NICHE_projects/Repo/Cloneables/tract/examples/pytorch-resnet/requirements.txt,False,CVE-2022-45907,">=0,<1.13.1","Torch 1.13.1 includes a fix for CVE-2022-45907: In PyTorch before trunk/89695, torch.jit.annotations.parse_type_line can cause arbitrary code execution because eval is used unsafely.
https://github.com/pytorch/pytorch/issues/88868"
